### ISSUE TITLE
Rendering FPS of example script is too low

### ISSUE THREAD

**Issue by feidieufo** [decisionforce/metadrive#100]
When I run 
python -m metadrive.examples.drive_in_single_agent_env
I found the fps is about 4 fps
I used the nvidia-smi command and found that my 2060gpu was not occupied.

I also can find some warnings about:
WARNING:root: It seems you don't install our cython utilities yet! Please reinstall MetaDrive via .........

**Comment by QuanyiLi** [comment]
Thanks for your feedback. Since metadrive can even run on a laptop with only integrated gpu, a 2060gpu is definitely satisfied the lowest requirements. Thus some strange problems may occur on your platform. Could you please tell us more information about your platform, such as your OS, CPU, and whether it is a laptop? 

Besides, the warning is thrown when running a history version of metadrive installed via pip. To find if the low fps is caused by this deprecated version,  you can try reinstalling metadrive via git and running the same script on the main branch.

**Comment by air-tea** [comment]
I have met the same problem.
I found the fps is only about 25 fps and I found my MX150 GPU was not occupied.
The OS is win10, CPU is i7-8550U, laptop(XiaoMi Pro).
I didn't get a warning.
![image](https://user-images.githubusercontent.com/51868302/142854530-1d380fbc-2153-40ae-bdbb-6a1e09981f3e.png)

However when I ran the simulation test, I find the FPS was around 200.
![image](https://user-images.githubusercontent.com/51868302/142854759-faad253f-2e5e-4f6f-b6b9-499f0c91ef87.png)

Thanks for your time!

**Comment by QuanyiLi** [comment]
Hi air-tea,

I guess the FPS=25 indicates that your rendering FPS is 25, which means the visualization FPS is low when the window is popped. The most possible reason is that you run MetaDrive on your integrated GPU instead of the discrete GPU(MX 150).
You can try to switch your GPU mode to discrete GPU to improve the visualization efficiency.

However, in the script for fps testing the observation is lidar, which means MetaDrive doesn't use GPU to render anything and MetaDrive will only use CPU to do calculations. Therefore, the FPS reported by this script is different from the rendering FPS and will not be restricted by rendering FPS.

If you want to train RL agents, feel free to begin, since rendering is disabled when training RL, and the FPS will not be limited by the rendering FPS. Therefore, this problem will only influence your visualization experience.

**Comment by air-tea** [comment]
Thanks for your answer! I switched the GPU mode and successfully improved the visualization. :smile:
